apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul-server
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      ekos-app: zuul-server
  template:
    metadata:
      labels:
        ekos-app: zuul-server
    spec:
      initContainers:
      - name: init-eureka
        image: registry.ekos.local/library/zuul-server
        command:
        - sh
        - "-c"
        - |
          set -ex
          
          PEERS=$(nslookup eureka 2>/dev/null | grep Address | awk '{print $4}' | awk '{printf("http://%s:8761/,",$1)}')
          DEFAULT_ZONE=${PEERS%,}
          arr=${DEFAULT_ZONE//,/ }
          for address in $arr; do
            info=`curl -s -m 10 --connect-timeout 10 -I $address`
              code=`echo $info|grep "HTTP"|awk '{print $2}'`
              if [ "$code" == "200" ];then
                 echo "...........................$code"
              else
                 echo "...........................$code"
                 exit 1
               fi
          done
      containers:
      - env:
        - name: CONFIG_SERVICE_NAME
          value: config-server
        image: registry.ekos.local/library/zuul-server
        name: zuul-server
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 500M
      volumeMounts:
        - name: config
          mountPath: /
      volumes:
      - name: config
        configMap:
          name: zuul-config      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zuul-config
  namespace: test
data:
  application.yml: |
   server:
     port: 7291
   eureka:
       instance:
           leaseExpirationDurationInSeconds: 2
           leaseRenewalIntervalInSeconds: 1
           preferIpAddress: true
       client:
           registerWithEureka: true
           fetchRegistry: true
           registryFetchIntervalSeconds: 3
           serviceUrl:
               defaultZone: http://eureka:8761/eureka/
   spring:
     application:
       name: zuul-server
     cloud:
       loadbalancer:
         retry:
           enabled: true
   ribbon:
     MaxAutoRetries: 1
     MaxAutoRetriesNextServer: 3
     OkToRetryOnAllOperations: true
     ConnectTimeout: 1500
     ReadTimeout: 2000
   hystrix:
     command:
       default:
         execution:
           isolation:
             thread:
               timeoutInMilliseconds: 1500
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-server
  namespace: test
spec:
  ports:
  - name: "7291"
    port: 7291
    protocol: TCP
    targetPort: 7291
  selector:
    ekos-app: zuul-server